version: "3.9"

networks:
  app: {}

services:  
  elastic:
    image: elasticsearch:7.16.2
    networks:
    - app
    environment:
      discovery.type: single-node
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    ports:
    - 9200:9200
    volumes:
    - ./data:/usr/share/elasticsearch/data

  kibana:
    image: kibana:7.16.2
    networks:
    - app
    environment:
      ELASTICSEARCH_HOSTS: '["http://elastic:9200"]'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5601/"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    ports:
    - 5601:5601

  generator:
    build: .
    networks:
    - app
    environment:
      ELASTICSEARCH_URL: http://elastic:9200
    restart: on-failure
    depends_on:
    - elastic
    scale: 3

